services:
  - type: web
    name: maison-backend
    env: node
    rootDir: Backend
    buildCommand: npm install && node scripts/initDB.js && node scripts/seedProducts.js
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 5000
